// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.fictionalrealm.osserc.protocol.sp;

public interface DisconnectionNoticeSPOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required .osserc.dt.DisconnectionReason reason = 1;
  boolean hasReason();
  com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason getReason();
  
  // optional string msg = 2;
  boolean hasMsg();
  String getMsg();
}
