// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.fictionalrealm.osserc.protocol.sp;

public  final class DisconnectionNoticeSP extends
    com.google.protobuf.GeneratedMessage
    implements DisconnectionNoticeSPOrBuilder {
  // Use DisconnectionNoticeSP.newBuilder() to construct.
  private DisconnectionNoticeSP(Builder builder) {
    super(builder);
  }
  private DisconnectionNoticeSP(boolean noInit) {}
  
  private static final DisconnectionNoticeSP defaultInstance;
  public static DisconnectionNoticeSP getDefaultInstance() {
    return defaultInstance;
  }
  
  public DisconnectionNoticeSP getDefaultInstanceForType() {
    return defaultInstance;
  }
  
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fictionalrealm.osserc.protocol.sp.ServerProtocol.internal_static_osserc_sp_DisconnectionNoticeSP_descriptor;
  }
  
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fictionalrealm.osserc.protocol.sp.ServerProtocol.internal_static_osserc_sp_DisconnectionNoticeSP_fieldAccessorTable;
  }
  
  private int bitField0_;
  // required .osserc.dt.DisconnectionReason reason = 1;
  public static final int REASON_FIELD_NUMBER = 1;
  private com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason reason_;
  public boolean hasReason() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  public com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason getReason() {
    return reason_;
  }
  
  // optional string msg = 2;
  public static final int MSG_FIELD_NUMBER = 2;
  private java.lang.Object msg_;
  public boolean hasMsg() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  public String getMsg() {
    java.lang.Object ref = msg_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (com.google.protobuf.Internal.isValidUtf8(bs)) {
        msg_ = s;
      }
      return s;
    }
  }
  private com.google.protobuf.ByteString getMsgBytes() {
    java.lang.Object ref = msg_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }
  
  private void initFields() {
    reason_ = com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason.SERVER_SHUTDOWN;
    msg_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;
    
    if (!hasReason()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }
  
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeEnum(1, reason_.getNumber());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getMsgBytes());
    }
    getUnknownFields().writeTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
  
    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, reason_.getNumber());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getMsgBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }
  
  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }
  
  public static com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  public static com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  
  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }
  
  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSPOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fictionalrealm.osserc.protocol.sp.ServerProtocol.internal_static_osserc_sp_DisconnectionNoticeSP_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fictionalrealm.osserc.protocol.sp.ServerProtocol.internal_static_osserc_sp_DisconnectionNoticeSP_fieldAccessorTable;
    }
    
    // Construct using com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }
    
    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }
    
    public Builder clear() {
      super.clear();
      reason_ = com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason.SERVER_SHUTDOWN;
      bitField0_ = (bitField0_ & ~0x00000001);
      msg_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    
    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }
    
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP.getDescriptor();
    }
    
    public com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP getDefaultInstanceForType() {
      return com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP.getDefaultInstance();
    }
    
    public com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP build() {
      com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }
    
    private com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP buildParsed()
        throws com.google.protobuf.InvalidProtocolBufferException {
      com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(
          result).asInvalidProtocolBufferException();
      }
      return result;
    }
    
    public com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP buildPartial() {
      com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP result = new com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.reason_ = reason_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.msg_ = msg_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }
    
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP) {
        return mergeFrom((com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }
    
    public Builder mergeFrom(com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP other) {
      if (other == com.fictionalrealm.osserc.protocol.sp.DisconnectionNoticeSP.getDefaultInstance()) return this;
      if (other.hasReason()) {
        setReason(other.getReason());
      }
      if (other.hasMsg()) {
        setMsg(other.getMsg());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }
    
    public final boolean isInitialized() {
      if (!hasReason()) {
        
        return false;
      }
      return true;
    }
    
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder(
          this.getUnknownFields());
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            this.setUnknownFields(unknownFields.build());
            onChanged();
            return this;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();
            com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason value = com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              reason_ = value;
            }
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            msg_ = input.readBytes();
            break;
          }
        }
      }
    }
    
    private int bitField0_;
    
    // required .osserc.dt.DisconnectionReason reason = 1;
    private com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason reason_ = com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason.SERVER_SHUTDOWN;
    public boolean hasReason() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason getReason() {
      return reason_;
    }
    public Builder setReason(com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      reason_ = value;
      onChanged();
      return this;
    }
    public Builder clearReason() {
      bitField0_ = (bitField0_ & ~0x00000001);
      reason_ = com.fictionalrealm.osserc.protocol.datatypes.DisconnectionReason.SERVER_SHUTDOWN;
      onChanged();
      return this;
    }
    
    // optional string msg = 2;
    private java.lang.Object msg_ = "";
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMsg() {
      java.lang.Object ref = msg_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    public Builder setMsg(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      msg_ = value;
      onChanged();
      return this;
    }
    public Builder clearMsg() {
      bitField0_ = (bitField0_ & ~0x00000002);
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    void setMsg(com.google.protobuf.ByteString value) {
      bitField0_ |= 0x00000002;
      msg_ = value;
      onChanged();
    }
    
    // @@protoc_insertion_point(builder_scope:osserc.sp.DisconnectionNoticeSP)
  }
  
  static {
    defaultInstance = new DisconnectionNoticeSP(true);
    defaultInstance.initFields();
  }
  
  // @@protoc_insertion_point(class_scope:osserc.sp.DisconnectionNoticeSP)
}

