// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.fictionalrealm.osserc.protocol.cp;

public interface InitUserOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required string username = 1;
  boolean hasUsername();
  String getUsername();
  
  // required string password = 2;
  boolean hasPassword();
  String getPassword();
  
  // optional string token = 3;
  boolean hasToken();
  String getToken();
}
