// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.fictionalrealm.osserc.protocol.sp;

public  final class WelcomeSP extends
    com.google.protobuf.GeneratedMessage
    implements WelcomeSPOrBuilder {
  // Use WelcomeSP.newBuilder() to construct.
  private WelcomeSP(Builder builder) {
    super(builder);
  }
  private WelcomeSP(boolean noInit) {}
  
  private static final WelcomeSP defaultInstance;
  public static WelcomeSP getDefaultInstance() {
    return defaultInstance;
  }
  
  public WelcomeSP getDefaultInstanceForType() {
    return defaultInstance;
  }
  
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fictionalrealm.osserc.protocol.sp.ServerProtocol.internal_static_osserc_sp_WelcomeSP_descriptor;
  }
  
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fictionalrealm.osserc.protocol.sp.ServerProtocol.internal_static_osserc_sp_WelcomeSP_fieldAccessorTable;
  }
  
  private int bitField0_;
  // required int32 version = 1;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  public int getVersion() {
    return version_;
  }
  
  // required .osserc.dt.ServerStatus serverStatus = 2;
  public static final int SERVERSTATUS_FIELD_NUMBER = 2;
  private com.fictionalrealm.osserc.protocol.datatypes.ServerStatus serverStatus_;
  public boolean hasServerStatus() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  public com.fictionalrealm.osserc.protocol.datatypes.ServerStatus getServerStatus() {
    return serverStatus_;
  }
  
  // optional string msg = 3;
  public static final int MSG_FIELD_NUMBER = 3;
  private Object msg_;
  public boolean hasMsg() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  public String getMsg() {
    Object ref = msg_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (com.google.protobuf.Internal.isValidUtf8(bs)) {
        msg_ = s;
      }
      return s;
    }
  }
  private com.google.protobuf.ByteString getMsgBytes() {
    Object ref = msg_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    version_ = 0;
    serverStatus_ = com.fictionalrealm.osserc.protocol.datatypes.ServerStatus.ONLINE;
    msg_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasVersion()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasServerStatus()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, version_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(2, serverStatus_.getNumber());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getMsgBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, serverStatus_.getNumber());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getMsgBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static WelcomeSP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static WelcomeSP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static WelcomeSP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static WelcomeSP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static WelcomeSP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static WelcomeSP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  public static WelcomeSP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static WelcomeSP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static WelcomeSP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static WelcomeSP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(WelcomeSP prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements WelcomeSPOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fictionalrealm.osserc.protocol.sp.ServerProtocol.internal_static_osserc_sp_WelcomeSP_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fictionalrealm.osserc.protocol.sp.ServerProtocol.internal_static_osserc_sp_WelcomeSP_fieldAccessorTable;
    }

    // Construct using com.fictionalrealm.osserc.protocol.sp.WelcomeSP.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      version_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      serverStatus_ = com.fictionalrealm.osserc.protocol.datatypes.ServerStatus.ONLINE;
      bitField0_ = (bitField0_ & ~0x00000002);
      msg_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return WelcomeSP.getDescriptor();
    }

    public WelcomeSP getDefaultInstanceForType() {
      return WelcomeSP.getDefaultInstance();
    }

    public WelcomeSP build() {
      WelcomeSP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    private WelcomeSP buildParsed()
        throws com.google.protobuf.InvalidProtocolBufferException {
      WelcomeSP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(
          result).asInvalidProtocolBufferException();
      }
      return result;
    }

    public WelcomeSP buildPartial() {
      WelcomeSP result = new WelcomeSP(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.version_ = version_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.serverStatus_ = serverStatus_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.msg_ = msg_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof WelcomeSP) {
        return mergeFrom((WelcomeSP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(WelcomeSP other) {
      if (other == WelcomeSP.getDefaultInstance()) return this;
      if (other.hasVersion()) {
        setVersion(other.getVersion());
      }
      if (other.hasServerStatus()) {
        setServerStatus(other.getServerStatus());
      }
      if (other.hasMsg()) {
        setMsg(other.getMsg());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasVersion()) {

        return false;
      }
      if (!hasServerStatus()) {

        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder(
          this.getUnknownFields());
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            this.setUnknownFields(unknownFields.build());
            onChanged();
            return this;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            version_ = input.readInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            com.fictionalrealm.osserc.protocol.datatypes.ServerStatus value = com.fictionalrealm.osserc.protocol.datatypes.ServerStatus.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              serverStatus_ = value;
            }
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            msg_ = input.readBytes();
            break;
          }
        }
      }
    }

    private int bitField0_;

    // required int32 version = 1;
    private int version_ ;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getVersion() {
      return version_;
    }
    public Builder setVersion(int value) {
      bitField0_ |= 0x00000001;
      version_ = value;
      onChanged();
      return this;
    }
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
      onChanged();
      return this;
    }

    // required .osserc.dt.ServerStatus serverStatus = 2;
    private com.fictionalrealm.osserc.protocol.datatypes.ServerStatus serverStatus_ = com.fictionalrealm.osserc.protocol.datatypes.ServerStatus.ONLINE;
    public boolean hasServerStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.fictionalrealm.osserc.protocol.datatypes.ServerStatus getServerStatus() {
      return serverStatus_;
    }
    public Builder setServerStatus(com.fictionalrealm.osserc.protocol.datatypes.ServerStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      serverStatus_ = value;
      onChanged();
      return this;
    }
    public Builder clearServerStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      serverStatus_ = com.fictionalrealm.osserc.protocol.datatypes.ServerStatus.ONLINE;
      onChanged();
      return this;
    }

    // optional string msg = 3;
    private Object msg_ = "";
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getMsg() {
      Object ref = msg_;
      if (!(ref instanceof String)) {
        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    public Builder setMsg(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      msg_ = value;
      onChanged();
      return this;
    }
    public Builder clearMsg() {
      bitField0_ = (bitField0_ & ~0x00000004);
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    void setMsg(com.google.protobuf.ByteString value) {
      bitField0_ |= 0x00000004;
      msg_ = value;
      onChanged();
    }
    
    // @@protoc_insertion_point(builder_scope:osserc.sp.WelcomeSP)
  }
  
  static {
    defaultInstance = new WelcomeSP(true);
    defaultInstance.initFields();
  }
  
  // @@protoc_insertion_point(class_scope:osserc.sp.WelcomeSP)
}

