// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.fictionalrealm.osserc.protocol.sp;

public interface WelcomeSPOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required int32 version = 1;
  boolean hasVersion();
  int getVersion();
  
  // required .osserc.dt.ServerStatus serverStatus = 2;
  boolean hasServerStatus();
  com.fictionalrealm.osserc.protocol.datatypes.ServerStatus getServerStatus();
  
  // optional string msg = 3;
  boolean hasMsg();
  String getMsg();
}
